### ISSUE TITLE
persistent webserver

### ISSUE THREAD

**Issue by mahmoudibrahim** [bihealth/scelvis#45]
Hi

Thank you for this wonderful tool to explore single cell data. 

I can run scelvis locally as described in the command line tutorial, which works perfectly. But I was wondering if there is documentation on how to deploy this as a persistent web server like the demo at https://scelvis-demo.bihealth.org ? 

many thanks!

best wishes
Mahmoud

**Comment by bobermayer** [comment]
Hi Mahmoud,

thanks for your interest in SCelVis. we actually just recently added a hosting tutorial [here](https://github.com/bihealth/scelvis/blob/hosting-tutorial/docs_manual/tutorial_hosting.rst). is that what you're looking for?

**Comment by mahmoudibrahim** [comment]
Hi Benedikt

yes, that's exactly what I meant : )

many thanks!
